# Generated by Django 3.1.1 on 2020-09-10 01:13

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('BookType', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('barcode', models.CharField(default='', max_length=20, primary_key=True, serialize=False, verbose_name='图书条形码')),
                ('bookName', models.CharField(default='', max_length=20, verbose_name='图书名称')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='图书价格')),
                ('count', models.IntegerField(default=0, verbose_name='图书库存')),
                ('publishDate', models.CharField(default='', max_length=20, verbose_name='出版日期')),
                ('publish', models.CharField(default='', max_length=20, verbose_name='出版社')),
                ('bookPhoto', models.ImageField(max_length='80', upload_to='img', verbose_name='图书图片')),
                ('bookDesc', tinymce.models.HTMLField(verbose_name='图书简介')),
                ('bookFile', models.FileField(max_length='100', upload_to='file', verbose_name='图书文件')),
                ('bookTypeObj', models.ForeignKey(db_column='bookTypeObj', on_delete=django.db.models.deletion.CASCADE, to='BookType.booktype', verbose_name='图书类别')),
            ],
            options={
                'verbose_name': '图书信息',
                'verbose_name_plural': '图书信息',
                'db_table': 't_Book',
            },
        ),
    ]
